auto_import:
  -
    filename: modules/custom/seatgeek_import/migrations/migrate_plus.migration.seatgeek_event.yml
    hash: ''
  -
    filename: modules/custom/seatgeek_import/migrations/migrate_plus.migration.seatgeek_performance.yml
    hash: ''
auto_export: {  }
_core:
  default_config_hash: W4OGMJ9g0nIliU6O4quijGqNLQuWFixbxzi1Fytx6lk
